# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build-classlib:
    name: Build class library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [ 'ne6.0', 'netstandard2.0' ]
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Run 'dotnet restore'
        run: dotnet restore "SmallsOnline.Subnetting.Lib.sln"
      - name: Run 'dotnet publish'
        run: dotnet publish "SmallsOnline.Subnetting.Lib.sln" --framework ${{ matrix.framework }}