on: [push, pull_request]
name: Build
jobs:
  build-classlib:
    name: Build class library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [ 'net5.0', 'netstandard2.0' ]
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Run 'dotnet restore'
        run: dotnet restore "SmallsOnline.Subnetting.sln"
      - name: Run 'dotnet publish'
        run: dotnet publish "SmallsOnline.Subnetting.sln" --framework ${{ matrix.framework }}
  build-pwsh-module:
    name: Build PowerShell module
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '5.0.x'
      - name: Run 'dotnet restore'
        run: dotnet restore "SmallsOnline.Subnetting.Pwsh.sln"
      - name: Run 'dotnet publish'
        run: dotnet publish "SmallsOnline.Subnetting.Pwsh.sln" --framework "netstandard2.0"
      - name: Run module build script
        shell: pwsh
        run: |
          .\buildModule.ps1 -ConfigurationName Release -SkipDotnetBuild