on: [push, pull_request]
name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [ 'net5.0', 'netstandard2.0' ]
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet restore
      - run: dotnet publish --framework ${{ matrix.framework }}
